---
title: "工作计划"
author: "Linda1103"
date: "2020/3/28"
output: html_document
---

  此次topic presantation报告内容包括以下几部分：研究内容、前期成果、eSIR模型的应用、疫情地图可视化
  
# 1.研究内容
 
  第一部分内容包括包括研究背景、研究主题、数据来源、方法与困难、小组其他成员介绍内容等。
    
##  1.1 研究背景
  
 包括疫情背景、文献综述。
    
## 1.2 研究主题
    
  （带括号的有余力可以做）
  
   1.以深圳市为例，通过运用宋学坤博士的eSIR模型计算疫情在深圳市的传染率、感染率。
   
   2.以深圳市400多个患者为节点绘制疫情地图，并实现可视化（最好是实现疫情传染网络地图可视化）
   
   3.寻找“零号病人”和“超级传播者”
   
   4.（绘制疫情个案知识谱系）
   
   5.运用空间计量方法分析深圳市疫情的时空传播特征和规律，（并运用之前的数据来做预测，或者运用其他省市数据来做检验和预测分析，适当调整，以此提升模型泛化能力）（本Topic不涉及空间计量的理论讲解）
   
   6.（制作疫情时空传播可视化网站）（通过此网站可以直观看到某地的疫情时空传播情况、重点感染地区、零号病人和超级感染者等）
       
## 1.3 数据来源
  
  本项目使用的数据是来自深圳市政府数据开放平台中“疫情数据开放”专题下的疫情数据集，截止3月15日，共9个数据集，由深圳市卫生健康委员会和市规划和自然资源局提供。
  
## 1.4 方法与困难
   
   本项目运用的方法主要包括描述性统计、可视化、空间计量分析方法、社会网络分析方法等。
  
   困难包括：
   
   1.代码能力弱，可视化代码难
  
   2.空间计量分析模型的构建及算法、代码的实现、
      
       
  ## 1.5 小组成员内容简介

# 2 前期成果

  前期成果有两种思路：
  
  1.可以根据现有的研究成果（截止3月3日），图表上传Rmd,但是要支持 code reproducible.
  
  2.根据更新到3月15日的数据，重新做一次描述性分析，并将图表上传Rmd.
  
# 3 eSIR模型的应用

### （需要把eSIR模型吃透，为后期预测全球性疫情传播打基础）

## 3.1 如何在R studio中下载eSIR包
   
## 3.2 eSIR模型的基本参数、微分方程、模型的解释
   
## 3.3 以深圳市数据为例，讲述eSIR模型的运用及简单解释（不需要讲运行结果的意义是什么，只需知道代码块的作用——比如建立怎样的模型或微分方程）

# 4 疫情地图可视化
  
## 4.1 基本疫情趋势可视化图表
    
   绘制下面图形，并实现可视化和动态化
    
   1、绘制环形图 [链接](https://blog.csdn.net/u014805893/article/details/70184172)
   
   2、线图，柱形图、花瓣图等
   
## 4.2 某市各乡、镇（街道）疫情地图（可以参考eSIR写的内容框架）
   
   1、以深圳市为例用python绘制疫情地图 [链接](https://blog.csdn.net/Androilly/article/details/104423107)
   
   2、用R绘制疫情地图 [链接](https://zhuanlan.zhihu.com/p/104584424?utm_source=wechat_timeline)
   
   3、代码讲解
   
   4、运行结果的意义

     
  
## 4.3 深圳市感染个例的疫情地图
  
   1、运用社会网络分析方法及可视化方法绘制疫情传播地图
   
   2、绘制时空变化动态地图
    
 
# 5 参考链接
        
## 1、GitHub可视化模板
  
[链接](https://github.com/statds/topic-presentation-tomkennon/blob/master/Introduction%20to%20Geospatial%20Visualizations.Rmd)

## 2、python常用可视化库
[链接](https://blog.csdn.net/chyuanrufeng/article/details/102960731?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522158527281819726869050524%2522%252C%2522scm%2522%253A%252220140713.130056874..%2522%257D&request_id=158527281819726869050524&biz_id=0&utm_source=distribute.pc_search_result.none-task)

## 3、疫情传播分析平台
[链接](https://blog.csdn.net/dQCFKyQDXYm3F8rB0/article/details/104285546)
