---
title: "深圳市COVID-19数据分析与可视化研究"
author: "Guardians of the Galaxy"
date: "2020/4/3"
pagemargins: 2.5 
fontsize: 12
mathjax: local
output: slidy_presentation
---
<style type="Data analysis and visualization of COVID-19 in Shenzhen/css">
	#header {
	    text-align: center;
	}
</style>
# 演讲内容

## 1、研究内容

&emsp;研究主题、研究思路、数据来源、研究方法、参考文献

## 2、前期成果

&emsp;1.对感染者性别、确诊人数等进行描述性统计分析

&emsp;2.运用Logistic回归模型探索影响患者病情轻重的因素

## 3、可视化方法1

&emsp;1、绘制深圳市各区累计确诊人数占比环形图

&emsp;2、深圳市各区累计确诊人数时序图

## 4、可视化方法2

&emsp;绘制深圳市累计确诊人数空间分布动态图（疫情地图）


# 1. 研究内容

## 1.1 研究主题

&emsp;&emsp;纵观当下，COVID—19已蔓延到全球200个国家和地区，已成为一起严重的全球性突发公共卫生事件，早日抑制疫情发展、恢复社会活力是全球人民的共同愿望。而深圳市作为全国性经济中心城市和国际化城市，也是我国拥有口岸数量和出入境人员最多的口岸城市，外来人员流动频繁。因此，研究深圳市COVID-19时空传播路径、特征及规律具有深刻意义。

&emsp;&emsp;本项目拟利用深圳市卫生健康局公开的418例新型冠状病毒肺炎病例流行病学调查数据，综合应用空间计量统计分析方法、数学统计方法、地理信息技术、可视化技术等，全面探讨深圳市COVID-19流行病学特征和传播的时空规律，剖析疫情传播的典型路径，为之后研究疫情预警机制提供基础，也为研究国内外疫情传播规律提供参考.


# 1.2研究思路

### 1.2.1分析深圳市COVID-19的流行病学特征

&emsp;&emsp;了解深圳市COVID-19的基本流行病学特征，是深入剖析深圳市疫情时空传播特征的前提。本项目拟从以下几个方面展开分析：

&emsp;1、描述性统计分析

&emsp;&emsp;本项目将运用典型相关分析、列联分析、二元logistic回归等方法初步分析深圳市患者的年龄、性别、是否有湖北直接接触史等人口统计特征与感染特征的关系。

&emsp;2、时序特征分析

&emsp;&emsp;通过绘制1月19日到3月5日的深圳市整体每日新增确诊人数变化时序图、深圳市各行政区每日新增人数时序变化图，分析深圳市疫情的整体发展态势（整体增幅、拐点、最低点）、阶段性特征及重点区域感染特征。

&emsp;3、空间分布特征

&emsp;&emsp;通过绘制深圳市累计确诊人数空间分布动态图，分析深圳市患者分布的整体特征、重点区域特征、时间变化特征等，初步探析深圳市疫情分布态势。


### 1.2.2 分析深圳市疫情时空传播规律

&emsp;&emsp;由于传染病在空间上的传播扩散与人口分布、环境及其他各类空间因子息息相关。感染者之间非完全独立,而是具备空间依赖性。因此需要运用空间统计分析方法探索感染者的空间关联关系。本项目将运用R、GeoDa等软件，利用Moran’s统计指数和LISA统计指数测度疫情全局空间自相关和局部空间自相关，对深圳市COVID-19的空间传播风险进行定量分析。

&emsp; 1、 全局空间自相关

&emsp;&emsp;全局空间自相关是从宏观的角度研究观测值在空间上的分布特征。由于性别、年龄、发病时间及是否有武汉直接接触史、累计确诊人数等都会对疫情的空间传播模式产生影响。本文将运用全局Moran'I来分析以上所有因素的的空间自相关性，从而分析深圳市疫情分布的总体时空特征。

&emsp; 2、 局部空间自相关

&emsp;&emsp;全局空间自相关是分析整个研究区域累计确诊人数、性别、年龄等各指标自身的相似程度，但是不能得知具体地区的空间分布模式。而局部空间自相关可以描述具体空间单元与其邻近单元观测值的相似程度。因此我们运用采用LISA指数来分析深圳市疫情的空间传播风险及其时空演化特征。

&emsp;&emsp;LISA 指数能够定量反映出空间上的4种聚类特征，分别是高-高聚集（高风险）、低-聚集、高-低聚集、低-高聚集。通过绘制累计确诊人数、性别、年龄、等LISA集聚集图，分析疫情传播的感染区域特征，思考形成疫情高风险区域的原因。并根据发病时间的LISA聚集图,分析不同时期疫情传播的空间特征，探索疫情传播时空规律。

# 1.3 数据来源

&emsp;&emsp;本项目使用的数据来自深圳市政府数据开放平台中“疫情数据开放”专题下的1月19日到3月5日的9个疫情数据集。数据集由深圳市卫生健康委员会和市规划和自然资源局提供。

&emsp;&emsp;数据包含深圳市418例COVID-19感染者基本信息，包括每位感染者的年龄、性别、居住地、与其他病例关系、行程、发病时间、入院时间、染病原因、病况等信息。我们根据研究需要对部分数据进行预处理，如将具体染病原因做有无湖北直接接触史划分、将居住地、病况等设置为虚拟变量等。

# 1.4 研究方法

### 1.4.1空间计量分析方法。

&emsp;&emsp;利用空间分析软件GeoDA进行基于Moran’sI和LISA统计指数的疫情传播风险分析。

### 1.4.2可视化分析方法

&emsp;&emsp;运用ggplot2、ggmap、maps、leaflet等绘制深圳市患者年龄—性别分布金字塔图、每日新增确诊人数变化时序图、累计确诊人数空间分布动态图等。
  
# 1.5 参考文献

[1]曹志冬,曾大军,郑晓龙,王全意,王飞跃,王劲峰,王小莉.北京市SARS流行的特征与时空传播规律[J].中国科学:地球科学,2010,40(06):776-788.

[2]刘郑倩,叶玉瑶,张虹鸥,郭洪旭,杨骥,王长建.珠海市新型冠状病毒肺炎聚集发生的时空特征及传播路径[J/OL].热带地理:1-13[2020-04-01].https://doi.org/10.13284/j.cnki.rddl.003228.

[3]苏理云,郭雯.中国各省新型冠状病毒肺炎累计确诊人数的空间聚集及时空格局演变分析[J/OL].重庆理工大学学报(自然科学):1-11[2020-04-01].http://kns.cnki.net/kcms/detail/50.1205.t.20200325.1548.002.html.

[4]王宣焯,廖聪慧,李志慧,胡欢,程晓敏,李芊璘,陆家海.广东省新型冠状病毒肺炎早期流行与时空分布情况初步分析[J/OL].热带医学杂志,2020(03):1-8[2020-04-01].http://kns.cnki.net/kcms/detail/44.1503.R.20200213.0806.002.html.

[5]张君涵,袁宗祥,黄颉刚,梁冰玉,刘洁,廖艳研,韦吴迪,潘沛江,梁浩,叶力.福建省新型冠状病毒肺炎流行特征与网络关注点初步分析[J].广西医学,2020,42(03):325-330.

[6]曹志冬,曾大军,王全意,王小莉,张奕,邓瑛,郑晓龙,王飞跃.北京市甲型H1N1早期流行的特征与时空演变模式[J].地理学报,2010,65(03):361-368.

[7]胡碧松,龚建华,周洁萍,孙麇,杨荔阳,夏宇.传播输入输出流的时空特征分析——以北京SARS流行为例[J].中国科学:地球科学,2013,43(09):1499-1517.

[8]徐冰. 基于贝叶斯网络的传染病时空预警模型研究[D].长安大学,2015.

[9]许小可,文成,张光耀,孙皓宸,刘波,王贤文.新冠肺炎爆发前期武汉外流人口的地理去向分布及影响[J/OL].电子科技大学学报:1-6[2020-04-01].http://kns.cnki.net/kcms/detail/51.1207.T.20200213.2002.002.html.

[10]王书霞,王晓峰,常月明.基于Moran'sI和LISA的人口与经济系统协调性研究[J].统计与决策,2014(06):90-93.

# 2.前期成果

# 3.可视化方法1

## 3.1 利用ggplot画深圳市各区确诊人数变化折线图


















